[package]
name = "crest"
version = "0.3.1"
authors = ["Pablo Couto <pablo@0x221e.net>"]

description = "A REST client library."
repository = "https://github.com/pablocouto/crest"
documentation = "https://pablocouto.github.io/crest/crest/index.html"
keywords = ["rest", "client"]
license = "Apache-2.0/MIT"

build = "build/build.rs"

exclude = [
    "build/travis.sh",
]

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "0.6", optional = true }
syntex = "0.26"

[dependencies]
hyper = "0.7"
serde = "0.6"
serde_json = "0.6"
serde_macros = { version = "0.6", optional = true }
url = "0.5"
