[package]
name = "crest"
version = "0.3.4"
authors = ["Pablo Couto <pablo@0x221e.net>"]

description = "A REST client library."
repository = "https://github.com/pablocouto/crest"
documentation = "https://pablocouto.github.io/crest/crest/index.html"
keywords = ["rest", "client"]
license = "Apache-2.0/MIT"

[dependencies]
hyper = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "0.5"
