[package]
name = "crest-next"
version = "0.1.0"
authors = ["Pablo Couto <pablo@uncharted.space>"]
publish = "false"

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
url = "1.5"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"